GET http://localhost:3001/api/persons

#######

GET http://localhost:3001/api/persons/2

###########

DELETE http://localhost:3001/api/persons/2

#########

GET http://localhost:3001/api/persons/2

######

GET http://localhost:3001/api/persons

########

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Tice Testin",
  "number": "02734093"
}

#########

GET http://localhost:3001/typo

#######################

GET https://fullstackopen-tice-phonebook.herokuapp.com/api/persons

#######

POST https://fullstackopen-tice-phonebook.herokuapp.com/api/persons
content-type: application/json

{
  "name": "Tice Testin",
  "number": "02734093"
}

##################
################
##################

GET http://localhost:3001/api/persons

#######

GET http://localhost:3001/api/persons/61001984c1bbaa0015b80854

#######

GET http://localhost:3001/api/persons/somewrongformat

###########

DELETE http://localhost:3001/api/persons/60ff0943b8177bd7027e1137

########

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Tice Testin",
  "number": "8765654"
}

#########

PUT http://localhost:3001/api/persons/610017fbbd1fcaf223660e6c
content-type: application/json

{
  "name": "Tice Testin",
  "number": "9873250234"
}